name: Deploy API to App Service

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/api/**'
      - '.github/workflows/api-deploy.yml'
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      APP_NAME: app-11plusplatform-dev-uks   # target App Service name
      API_DIR: apps/api

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: ${{ env.API_DIR }}/package-lock.json

      - name: Install deps
        working-directory: ${{ env.API_DIR }}
        run: npm ci

      - name: Build
        working-directory: ${{ env.API_DIR }}
        run: npm run build

      # Deploy the source and let Oryx build on App Service (most reliable)
      # Set SCM_DO_BUILD_DURING_DEPLOYMENT=true in App Settings (step 3).
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.APP_NAME }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_API }}
          package: ${{ env.API_DIR }}