name: SWA Build & Deploy (Next.js static export)

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'false'
          fetch-depth: 0

      - name: Use Node 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: apps/web/package-lock.json

      - name: Install (strict, app folder)
        working-directory: apps/web
        run: npm ci

      - name: Build (Next.js → out/)
        working-directory: apps/web
        run: npm run build
        # (env not required if apps/web/.env.production is committed)

      - name: Deploy to Azure Static Web Apps (upload prebuilt)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: 'upload'
          skip_app_build: true
          app_artifact_location: 'apps/web/out'
