name: SWA Build & Deploy (Next.js static export)

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'false'
          fetch-depth: 0

      - name: Use Node 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: apps/web/package-lock.json

      - name: Install deps (allow platform binaries)
        working-directory: apps/web
        env:
          NPM_CONFIG_FROZEN_LOCKFILE: 'false'
        run: npm install

      - name: Build (Next.js → out/)
        working-directory: apps/web
        env:
          # Keep if lightningcss causes issues on Linux; remove later if you like
          NEXT_DISABLE_LIGHTNINGCSS: '1'
        run: npm run build

      - name: Verify build artifact exists
        run: |
          ls -la apps/web/out || (echo "out/ not found" && exit 1)

      - name: Verify SWA token present
        run: |
          if [ -z "${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}" ]; then
            echo "Missing AZURE_STATIC_WEB_APPS_API_TOKEN secret"; exit 1;
          else
            echo "SWA token detected";
          fi

      - name: Deploy to Azure Static Web Apps (upload prebuilt)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload
          skip_app_build: true
          app_location: ''                 # root (we're just uploading an artifact)
          app_artifact_location: apps/web/out
